        <nav id="nav">
            <ul>
                <li><a href="#">Home</a></li>
                <li>
                    <a href="#">Lectures</a>
                    <ul>
                <li><a href="http://teams.thenet.ca/meatloaf/proto-site/index.shtml">Home</a></li>
                <li>
                    <a href="http://teams.thenet.ca/meatloaf/proto-site/lectures/index.shtml">Lectures</a>
                    <ul id="lectures">
                        <li>01 | Introduction</li>
                        <li>02 | Tools &amp; standards</li>
                        <li>03 | HTML 5 &amp; SEO</li>
                        <li><a href="http://teams.thenet.ca/meatloaf/proto-site/lectures/lecture4/index.shtml">04 | CSS concepts</a></li>
                        <li>05 | More CSS</li>
                        <li>06 | CSS and SSIs</li>
                        <li>07 | Template development</li>
                        <li>08 | Develpment methodology</li>
                        <li>09 | Behaviour</li>
                        <li>10 | Source Control GIT</li>
                    </ul>
                </li>
                <li>Course news in Blog</li>
                <li><a href="http://teams.thenet.ca/meatloaf/proto-site/references/index.shtml">References</a></li>
                <li><a href="http://teams.thenet.ca/meatloaf/proto-site/assignments/index.shtml">Assignments</a></li>
                <li>Site Map</li>
            </ul>
                </li>
                <li><a href="http://bcit1950meatloaf.tumblr.com/">Course in Blog</a></li>
                <li><a href="http://teams.thenet.ca/meatloaf/proto-site/references/index.shtml">References</a></li>
                <li><a href="http://teams.thenet.ca/meatloaf/proto-site/assignments/index.shtml">Assignments</a></li>
                <li><a href="#">Site Map</a></li>
            </ul>
        </nav>