        <nav id="nav">
            <ul>
                <li><a href="#">Home</a></li>
                <li>
                    <a href="#">Lectures</a>
                    <ul>
                        <li><a href="#">01</a><ul><li>Introduction</li></ul></li>
                         <li><a href="#">02</a><ul><li>Tools &amp; standards</li></ul></li>
                         <li><a href="#">03</a><ul><li>HTML 5 &amp; SEO</li></ul></li>
                         <li><a href="http://teams.thenet.ca/meatloaf/proto-site/lectures/lecture4/index.shtml">04</a><ul><li>CSS concepts</li></ul></li>
                         <li><a href="#">05</a><ul><li>More CSS</li></ul></li>
                         <li><a href="#">06</a><ul><li>CSS and SSIs</li></ul></li>
                         <li><a href="#">07</a><ul><li>Template development</li></ul></li>
                         <li><a href="#">08</a><ul><li>Develpment methodology</li></ul></li>
                         <li><a href="#">09</a><ul><li>Behaviour</li></ul></li>
                         <li><a href="#">10</a><ul><li>Source Control GIT</li></ul></li>
                    </ul>
                </li>
                <li><a href="#">Course in Blog</a></li>
                <li><a href="http://teams.thenet.ca/meatloaf/proto-site/references/index.shtml">References</a></li>
                <li><a href="http://teams.thenet.ca/meatloaf/proto-site/assignments/index.shtml">Assignments</a></li>
                <li><a href="#">Site Map</a></li>
            </ul>
        </nav>